server:
  port: 8085

spring:
  application:
    name: config-server
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  cloud:
    config:
      server:
        git:
          uri: https://github.com/duchong001/spring-cloud-config.git #GitHub上面的git仓库名字
          #git 仓库的账号密码 私有仓库需要配置
          #username: ***
          #password: ***

#eureka 注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
        hostname: localhost
        #显ip
        prefer-ip-address: true
        #eureka 中心显示的服务名
        instance-id: ${spring.application.name}-${server.port}


#日志
logging:
  file: config-server.log
